name: Daily Weather to Feishu

on:
  schedule:
    - cron: '26 00 * * *'   # UTC 23:00 = 北京时间次日 7:00
  workflow_dispatch:        # 允许手动触发测试

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests==2.*

      - name: Run weather bot
        run: python weather_bot.py
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          CITY: ${{ secrets.CITY }}
